### ISSUE TITLE
Failed to upload snapshot in minio s3 

### ISSUE THREAD

**Issue by sharmavijay86** [vmware-tanzu/velero-plugin-for-vsphere#156] opened 2020-08-11 13:19 UTC
Hi Team,
i am currently testing this feature for **block provisioner   csi.vsphere.vmware.com**  in my airgapped tkg environment on vsphere 6.7u3.

The problem here is , when i am taking backup as bellow   
```
 velero backup create my-backup --include-namespaces=nginx-example --snapshot-volumes --volume-snapshot-locations vsphere
```
Backup completed partially success.

```
~$ velero backup describe my-backup
Name:         my-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.3+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  PartiallyFailed (run `velero backup logs my-backup` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  nginx-example
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-08-11 13:07:34 +0000 UTC
Completed:  2020-08-11 13:07:43 +0000 UTC

Expiration:  2020-09-10 13:07:34 +0000 UTC

Total items to be backed up:  27
Items backed up:              27

Velero-Native Snapshots:  1 of 1 snapshots completed successfully (specify --details for more information)
```

Now when i am runing to check snapshot upload  it gives upload failed.

```
~$ kubectl get -n velero uploads.veleroplugin.io -o yaml
```
Bello is error

```
  status:
    currentBackOff: 32
    message: 'Failed to upload snapshot, ivd:11959489-aecd-48e0-8634-4728b7dc59a9:be658bf6-ed86-438d-abc9-829917bde84a,
      to durable object storage. Prepare for access failed. The error code is 3014.
      with error code: 3014'
    nextRetryTimestamp: "2020-08-11T13:50:46Z"
    phase: UploadError
    processingNode: gks-rat-stg-3-md-0-7659ffb99f-74m9g
    progress: {}
    retryCount: 6
    startTimestamp: "2020-08-11T13:07:43Z"
```
If you can help in what causing this error.

**Comment by lintongj** [comment] 2020-08-11 16:53
It indicates an issue of insufficient permission with your vSphere User. Please refer to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/108 for more detail.

**Comment by sharmavijay86** [comment] 2020-08-12 10:37
@lintongj  Hi mate. This is strange as we have admin privileges assigned for CSI user in TKG. Still we have same issue.

This is out put of backup describe 
 **kubectl logs velero-6b97c84c8b-jv8x9 -n velero**
```
time="2020-08-12T10:31:52Z" level=info msg="Ready to call astrolabe Snapshot API. Will retry on InvalidState error once per second for an hour at maximum" backup=velero/my-backup cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/snapshotmgr/snapshot_manager.go:122" pluginName=velero-plugin-for-vsphere
time="2020-08-12T10:31:52Z" level=info msg="CreateSnapshot called on IVD Protected Entity, ivd:11959489-aecd-48e0-8634-4728b7dc59a9" backup=velero/my-backup cmd=/plugins/velero-plugin-for-vsphere logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity.go:288" pluginName=velero-plugin-for-vsphere
time="2020-08-12T10:31:52Z" level=info msg="Retrying CreateSnapshot on IVD Protected Entity, ivd:11959489-aecd-48e0-8634-4728b7dc59a9, for one hour at the maximum" backup=velero/my-backup cmd=/plugins/velero-plugin-for-vsphere logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity.go:291" pluginName=velero-plugin-for-vsphere
time="2020-08-12T10:31:57Z" level=info msg="CreateSnapshot completed on IVD Protected Entity, ivd:11959489-aecd-48e0-8634-4728b7dc59a9, with the new snapshot, 66ffae14-428e-4c44-a3a1-a09057b54c9b, being created" backup=velero/my-backup cmd=/plugins/velero-plugin-for-vsphere logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity.go:332" pluginName=velero-plugin-for-vsphere
time="2020-08-12T10:31:57Z" level=info msg="Local IVD snapshot is created, ivd:11959489-aecd-48e0-8634-4728b7dc59a9:66ffae14-428e-4c44-a3a1-a09057b54c9b" backup=velero/my-backup cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/snapshotmgr/snapshot_manager.go:146" pluginName=velero-plugin-for-vsphere
time="2020-08-12T10:31:57Z" level=info msg="Start creating Upload CR" backup=velero/my-backup cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/snapshotmgr/snapshot_manager.go:155" pluginName=velero-plugin-for-vsphere
time="2020-08-12T10:31:57Z" level=info msg="CreateSnapshot completed with snapshotID, ivd:11959489-aecd-48e0-8634-4728b7dc59a9:66ffae14-428e-4c44-a3a1-a09057b54c9b" backup=velero/my-backup cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/volume_snapshotter_plugin.go:125" pluginName=velero-plugin-for-vsphere
time="2020-08-12T10:31:57Z" level=info msg="Executing custom action" backup=velero/my-backup logSource="pkg/backup/item_backupper.go:326" name=nginx-logs namespace=nginx-example resource=persistentvolumeclaims
time="2020-08-12T10:31:57Z" level=info msg="Starting PVCBackupItemAction" backup=velero/my-backup cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:57" pluginName=velero-plugin-for-csi
time="2020-08-12T10:31:57Z" level=info msg="Fetching storage class for PV fast" backup=velero/my-backup cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:101" pluginName=velero-plugin-for-csi
time="2020-08-12T10:31:57Z" level=info msg="running exec hook" backup=velero/my-backup hookCommand="[/sbin/fsfreeze --unfreeze /var/log/nginx]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=post hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:124" name=nginx-deployment-5ff6658c6-8vzmb namespace=nginx-example resource=pods
time="2020-08-12T10:31:57Z" level=info msg="stdout: " backup=velero/my-backup hookCommand="[/sbin/fsfreeze --unfreeze /var/log/nginx]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=post hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:171" name=nginx-deployment-5ff6658c6-8vzmb namespace=nginx-example resource=pods
time="2020-08-12T10:31:57Z" level=info msg="stderr: " backup=velero/my-backup hookCommand="[/sbin/fsfreeze --unfreeze /var/log/nginx]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=post hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:172" name=nginx-deployment-5ff6658c6-8vzmb namespace=nginx-example resource=pods
time="2020-08-12T10:31:57Z" level=info msg="1 errors encountered backup up item" backup=velero/my-backup logSource="pkg/backup/backup.go:444" name=nginx-deployment-5ff6658c6-8vzmb
time="2020-08-12T10:31:57Z" level=error msg="Error backing up item" backup=velero/my-backup error="error executing custom action (groupResource=persistentvolumeclaims, namespace=nginx-example, name=nginx-logs): rpc error: code = Unknown desc = failed to get volumesnapshotclass for storageclass fast: error listing volumesnapshot classes: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)" logSource="pkg/backup/backup.go:448" name=nginx-deployment-5ff6658c6-8vzmb
```

```
$ velero get backup
NAME        STATUS            ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
my-backup   PartiallyFailed   1        0          2020-08-12 10:31:49 +0000 UTC   29d       default            <none>

```

```
~$ velero backup describe my-backup
Name:         my-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.3+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  PartiallyFailed (run `velero backup logs my-backup` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  nginx-example
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-08-12 10:31:49 +0000 UTC
Completed:  2020-08-12 10:31:57 +0000 UTC

Expiration:  2020-09-11 10:31:49 +0000 UTC

Total items to be backed up:  12
Items backed up:              12

Velero-Native Snapshots:  1 of 1 snapshots completed successfully (specify --details for more information)
```

**Comment by lintongj** [comment] 2020-08-12 17:02
> This is strange as we have admin privileges assigned for CSI user in TKG. Still we have same issue.

This is weird. But the error code actually indicates the permission insufficiency. Do you mean the VC credential in CSI secret is associated with a user with admin privilege?

Also, would you please share the VDDK log available on data manager pod running on the node, gks-rat-stg-3-md-0-7659ffb99f-74m9g, where the error was observed? The step is shown below.

1. Find the pod. `kubectl -n velero get pods -o wide | grep datamgr | grep gks-rat-stg-3-md-0-7659ffb99f-74m9g | awk '{print $1}'`
2. Dowload the VDDK log. `kubectl cp velero/<pod name found in step>:/tmp/vmware-root/vixDiskLib-*.log <any local path you like>`

**Comment by sharmavijay86** [comment] 2020-08-14 06:27
@lintongj 
Here are details you wanted.
```
~$ kubectl -n velero get pods -o wide | grep datamgr | grep gks-rat-stg-3-md-0-7659ffb99f-74m9g | awk '{print $1}'
datamgr-for-vsphere-plugin-k5qpf
```

**Comment by sophie128** [comment] 2020-08-14 18:28
> @lintongj
> Here are details you wanted.
> 
> ```
> ~$ kubectl -n velero get pods -o wide | grep datamgr | grep gks-rat-stg-3-md-0-7659ffb99f-74m9g | awk '{print $1}'
> datamgr-for-vsphere-plugin-k5qpf
> ```

@sharmavijay86 
Do you have chance to continue executing the second step and see any VDDK log?

**Comment by lintongj** [comment] 2020-08-14 19:08
> @lintongj
> Here are details you wanted.
> 
> ```
> ~$ kubectl -n velero get pods -o wide | grep datamgr | grep gks-rat-stg-3-md-0-7659ffb99f-74m9g | awk '{print $1}'
> datamgr-for-vsphere-plugin-k5qpf
> ```

@sharmavijay86 
Did you have any chance to continue executing the command in the second step and see any VDDK log?

**Comment by longwa** [comment] 2020-08-16 17:51
I am seeing the same issue as well. My backup actually says it completed, but when I view uploads, they are retrying with the error message:
```
  status:
    currentBackOff: 16
    message: 'Failed to upload snapshot, ivd:7e15fbcf-aa75-4162-a11a-3a84e987ec1d:d12d3b07-95d6-488c-9a99-56ea946de51b,
      to durable object storage. Prepare for access failed. The error code is 3014.
      with error code: 3014'
```
Other parts of the backup are successfully uploaded to MinIO.

**Comment by danielkucera** [comment] 2020-08-17 08:39
I have similar problem in #159 . Can you show datamgr logs? Mine shows some cert error.

**Comment by longwa** [comment] 2020-08-17 16:31
I don't have any errors in the datamgr logs, just retries:
```
datamgr-for-vsphere-plugin-fjh2m:time="2020-08-17T16:27:46Z" level=info msg="Filtering out the retry upload request which comes in before next retry time" controller=upload generation=89 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/control │
│ ler/upload_controller.go:111" name=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=velero phase=UploadError                                                                                                                                                           │
│ datamgr-for-vsphere-plugin-fjh2m:time="2020-08-17T16:27:46Z" level=info msg="Ignore retry upload request which comes in before next retry time, upload CR: upload-d12d3b07-95d6-488c-9a99-56ea946de51b" controller=upload currentTime="2020-08-17 16:27:46.411481379 +0000  │
│ UTC m=+330.427574132" generation=89 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:117" name=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=velero nextRetryTime="2020-08-17 16:31:58 +0000 UTC" phase=Upl │
│ oadError
```

**Comment by longwa** [comment] 2020-08-17 16:36
Actually, in the vix logs, I do have a different permission error now:
```
VixDiskLib_PrepareForAccess: Disable Storage VMotion failed. Error 3014 (Insufficient permissions in the host operating system) (No permission to perform this action.) at 5001.
```
Following other issue suggestions, we added the Global -> Licenses, Global -> Enable/Disable Methods. Perhaps there are additional permissions needed?

**Comment by lintongj** [comment] 2020-08-17 18:30
@longwa thanks for your information.

> I don't have any errors in the datamgr logs, just retries:
> 
> ```
> datamgr-for-vsphere-plugin-fjh2m:time="2020-08-17T16:27:46Z" level=info msg="Filtering out the retry upload request which comes in before next retry time" controller=upload generation=89 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/control │
> │ ler/upload_controller.go:111" name=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=velero phase=UploadError                                                                                                                                                           │
> │ datamgr-for-vsphere-plugin-fjh2m:time="2020-08-17T16:27:46Z" level=info msg="Ignore retry upload request which comes in before next retry time, upload CR: upload-d12d3b07-95d6-488c-9a99-56ea946de51b" controller=upload currentTime="2020-08-17 16:27:46.411481379 +0000  │
> │ UTC m=+330.427574132" generation=89 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:117" name=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=velero nextRetryTime="2020-08-17 16:31:58 +0000 UTC" phase=Upl │
> │ oadError
> ```

There should be log messages in datamgr log that indicates the failure. Please take a look at the datamgr pod that runs on the same node which is shown in the `status.processingNode` field in upload CR. 



> Actually, in the vix logs, I do have a different permission error now:
> 
> ```
> VixDiskLib_PrepareForAccess: Disable Storage VMotion failed. Error 3014 (Insufficient permissions in the host operating system) (No permission to perform this action.) at 5001.
> ```
> 
> Following other issue suggestions, we added the Global -> Licenses, Global -> Enable/Disable Methods. Perhaps there are additional permissions needed?

As far as we know, these are permissions required. I am looking for help from VDDK team internally. It would be helpful to share your setup,

- versions of velero, velero-plugin-for-vsphere, vSphere,
- k8s cluster type
and more context of the failure in vddk log.

**Comment by danielkucera** [comment] 2020-08-17 18:47
After inspecting `/tmp/vmware-root/vixDiskLib-1.log` it seems that I have a similar issue:
```
2020-08-17T18:41:17.807Z| host-13| I125: VixDiskLib: VixDiskLib_PrepareForAccess: Prepare to access disk.
2020-08-17T18:41:17.807Z| host-13| I125: VixDiskLib: VixDiskLib_Connect: Establish connection.
2020-08-17T18:41:17.807Z| host-13| I125: VixDiskLib: Resolve host.
2020-08-17T18:41:18.267Z| host-13| E110: VixDiskLib: VixDiskLib_PrepareForAccess: Disable Storage VMotion failed. Error 3014 (Insufficient permissions in the host operating system) (No permission to perform this action.) at 5001.
2020-08-17T18:41:18.267Z| host-13| I125: VixDiskLib: VixDiskLib_FreeConnectParams: Free connection parameters.
```

**Comment by longwa** [comment] 2020-08-17 20:15
@lintongj I have also opened a support case with VMWare TKG team regarding this issue.

I'm running velero 1.4.2, plugin version 1.0.1, vsphere 6.7U3.
The k8s cluster is a TKG cluster, version 1.1.2 (k8s version 1.18.3).

**Comment by longwa** [comment] 2020-08-17 20:15
I found the relevant DataMgr logs:
```
I0817 18:32:01.732829       1 leaderelection.go:242] attempting to acquire leader lease  velero/upload-lease.upload-d12d3b07-95d6-488c-9a99-56ea946de51b...                                                                                                                 │
│ I0817 18:32:01.738110       1 leaderelection.go:252] successfully acquired lease velero/upload-lease.upload-d12d3b07-95d6-488c-9a99-56ea946de51b                                                                                                                            │
│ time="2020-08-17T18:32:01Z" level=info msg="Upload starting" controller=upload generation=97 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:232" name=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=veler │
│ o phase=UploadError                                                                                                                                                                                                                                                         │
│ time="2020-08-17T18:32:01Z" level=info msg="Upload request updated by retrieving from kubernetes API server" controller=upload generation=97 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:245" name=upload-d12d │
│ 3b07-95d6-488c-9a99-56ea946de51b namespace=velero phase=UploadError                                                                                                                                                                                                         │
│ time="2020-08-17T18:32:01Z" level=info msg="Filtering out the retry upload request which comes in before next retry time" controller=upload generation=98 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:111" nam │
│ e=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=velero phase=InProgress                                                                                                                                                                                             │
│ time="2020-08-17T18:32:01Z" level=info msg="Ignore retry upload request which comes in before next retry time, upload CR: upload-d12d3b07-95d6-488c-9a99-56ea946de51b" controller=upload currentTime="2020-08-17 18:32:01.745923514 +0000 UTC m=+7777.350652593" generation │
│ =98 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:117" name=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=velero nextRetryTime="2020-08-17 19:32:01 +0000 UTC" phase=InProgress                          │
│ time="2020-08-17T18:32:01Z" level=info msg="Upload status updated from UploadError to InProgress" controller=upload generation=97 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:401" name=upload-d12d3b07-95d6-4 │
│ 88c-9a99-56ea946de51b namespace=velero phase=UploadError                                                                                                                                                                                                                    │
│ 2020/08/17 18:32:01 pei = ivd:7e15fbcf-aa75-4162-a11a-3a84e987ec1d:d12d3b07-95d6-488c-9a99-56ea946de51b                                                                                                                                                                     │
│ time="2020-08-17T18:32:01Z" level=info msg="Copying the snapshot from local to remote repository" Local PEID="ivd:7e15fbcf-aa75-4162-a11a-3a84e987ec1d:d12d3b07-95d6-488c-9a99-56ea946de51b" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/dataM │
│ over/data_mover.go:84"                                                                                                                                                                                                                                                      │
│ 2020-08-17T18:32:02.093Z warning -[00008] [Originator@6876 sub=vimaccess] cannot get thumbprint: SSL error code '151441516', exception: 'Wrong X.509 Certificate format'                                                                                                    │
│ 2020-08-17T18:32:02.094Z warning -[00032] [Originator@6876 sub=Default] Closing Response processing in unexpected state: 3                                                                                                                                                  │
│ time="2020-08-17T18:32:02Z" level=error msg="Failed at copying to remote repository" Local PEID="ivd:7e15fbcf-aa75-4162-a11a-3a84e987ec1d:d12d3b07-95d6-488c-9a99-56ea946de51b" error="Prepare for access failed. The error code is 3014. with error code: 3014" error.file │
│ ="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity.go:70" error.function=github.com/vmware-tanzu/astrolabe/pkg/ivd.IVDProtectedEntity.GetDataReader logSource="/go/src/github.com/vmware-tanzu/velero-plugin │
│ -for-vsphere/pkg/dataMover/data_mover.go:96"
```

**Comment by lintongj** [comment] 2020-08-17 20:57
> @lintongj I have also opened a support case with VMWare TKG team regarding this issue.
> 
> I'm running velero 1.4.2, plugin version 1.0.1, vsphere 6.7U3.
> The k8s cluster is a TKG cluster, version 1.1.2 (k8s version 1.18.3).

Great. 

> I found the relevant DataMgr logs:
> 
> ```
> I0817 18:32:01.732829       1 leaderelection.go:242] attempting to acquire leader lease  velero/upload-lease.upload-d12d3b07-95d6-488c-9a99-56ea946de51b...                                                                                                                 │
> │ I0817 18:32:01.738110       1 leaderelection.go:252] successfully acquired lease velero/upload-lease.upload-d12d3b07-95d6-488c-9a99-56ea946de51b                                                                                                                            │
> │ time="2020-08-17T18:32:01Z" level=info msg="Upload starting" controller=upload generation=97 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:232" name=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=veler │
> │ o phase=UploadError                                                                                                                                                                                                                                                         │
> │ time="2020-08-17T18:32:01Z" level=info msg="Upload request updated by retrieving from kubernetes API server" controller=upload generation=97 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:245" name=upload-d12d │
> │ 3b07-95d6-488c-9a99-56ea946de51b namespace=velero phase=UploadError                                                                                                                                                                                                         │
> │ time="2020-08-17T18:32:01Z" level=info msg="Filtering out the retry upload request which comes in before next retry time" controller=upload generation=98 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:111" nam │
> │ e=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=velero phase=InProgress                                                                                                                                                                                             │
> │ time="2020-08-17T18:32:01Z" level=info msg="Ignore retry upload request which comes in before next retry time, upload CR: upload-d12d3b07-95d6-488c-9a99-56ea946de51b" controller=upload currentTime="2020-08-17 18:32:01.745923514 +0000 UTC m=+7777.350652593" generation │
> │ =98 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:117" name=upload-d12d3b07-95d6-488c-9a99-56ea946de51b namespace=velero nextRetryTime="2020-08-17 19:32:01 +0000 UTC" phase=InProgress                          │
> │ time="2020-08-17T18:32:01Z" level=info msg="Upload status updated from UploadError to InProgress" controller=upload generation=97 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:401" name=upload-d12d3b07-95d6-4 │
> │ 88c-9a99-56ea946de51b namespace=velero phase=UploadError                                                                                                                                                                                                                    │
> │ 2020/08/17 18:32:01 pei = ivd:7e15fbcf-aa75-4162-a11a-3a84e987ec1d:d12d3b07-95d6-488c-9a99-56ea946de51b                                                                                                                                                                     │
> │ time="2020-08-17T18:32:01Z" level=info msg="Copying the snapshot from local to remote repository" Local PEID="ivd:7e15fbcf-aa75-4162-a11a-3a84e987ec1d:d12d3b07-95d6-488c-9a99-56ea946de51b" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/dataM │
> │ over/data_mover.go:84"                                                                                                                                                                                                                                                      │
> │ 2020-08-17T18:32:02.093Z warning -[00008] [Originator@6876 sub=vimaccess] cannot get thumbprint: SSL error code '151441516', exception: 'Wrong X.509 Certificate format'                                                                                                    │
> │ 2020-08-17T18:32:02.094Z warning -[00032] [Originator@6876 sub=Default] Closing Response processing in unexpected state: 3                                                                                                                                                  │
> │ time="2020-08-17T18:32:02Z" level=error msg="Failed at copying to remote repository" Local PEID="ivd:7e15fbcf-aa75-4162-a11a-3a84e987ec1d:d12d3b07-95d6-488c-9a99-56ea946de51b" error="Prepare for access failed. The error code is 3014. with error code: 3014" error.file │
> │ ="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity.go:70" error.function=github.com/vmware-tanzu/astrolabe/pkg/ivd.IVDProtectedEntity.GetDataReader logSource="/go/src/github.com/vmware-tanzu/velero-plugin │
> │ -for-vsphere/pkg/dataMover/data_mover.go:96"
> ```

Would you please upload more VDDK log about this failure (the whole VDDK log if possible), so that we can involve VDDK team to help investigate this issue? Thanks @longwa.

**Comment by longwa** [comment] 2020-08-17 21:09
[vixDiskLib-1.log](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/5086817/vixDiskLib-1.log)

**Comment by longwa** [comment] 2020-08-17 23:37
After working with VMWare support, we were able to fix the problem and successfully upload a snapshot. 

The main issue is that we were missing the roles in VEEAM KB article plus they MUST BE AT THE vCenter level. Assigning them at the DataCenter or Cluster level will not work.

**Comment by lintongj** [comment] 2020-08-17 23:53
> After working with VMWare support, we were able to fix the problem and successfully upload a snapshot.
> 
> The main issue is that, in addition to the missing roles from the VEEAM KB article, the roles MUST BE AT THE vCenter level. Assigning them at the DataCenter or Cluster level will not work.

There are 2 issues
- Additional perms needed for TKG Role. In our case, they are `Global -> Licenses, Global -> Enable/Disable Methods`. 
- The TKG Role needs to be propagated at vCenter level.

TKG document, https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.1/vmware-tanzu-kubernetes-grid-11/GUID-install-tkg-vsphere.html#vsphere-permissions, will be updated soon.

**Comment by danielkucera** [comment] 2020-08-18 06:52
@lintongj thanks for clarifying required privileges.
The problem is that we are running on a shared infrastructure inside our company and ESX admins will NEVER give us such high and dangerous privileges. Is there any way around this? 
E.g. only throw warning when "Disable Storage VMotion" fails and accept the risks?

**Comment by danielkucera** [comment] 2020-08-18 09:17
I have worked around this issue but now I am hitting #145 🤦

**Comment by nrb** [comment] 2020-09-03 18:31
@lintongj Are you owning this?

**Comment by lintongj** [comment] 2020-09-03 19:01
@nrb Not yet. But, I will assign it to myself and update the documentation.

**Closed** 2020-09-09 16:43 UTC
Labels: documentation

**Comment by amos-baron** [comment] 2021-04-15 20:43
is there any work around for this issue? we are also on a shared infrastructure inside our company and ESX admins wont give us the necessary permissions on VC level
